---
title: "ngs_LMIC_exploration"
output: html_document
---
This script looks at LMICs and 


```{r}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
library(tidyverse) # data wrangling
library(tibble) # data wrangling
library(janitor) # column naming
library(countrycode) # country codes
library(lubridate) # date times
library(readxl) # excel import
library(zoo) # calculate rolling averages
library(R.utils) # R utilities
library(stringr) # to parse strings in R
library(tsoutliers) # remove outliers
library(dplyr) # data wrangling
library(cowplot)
library(car)
library(rgdal)
 
theme_set(theme_cowplot())
ggplot + background_grid(major = "xy", minor = "xy")
FIND_MAP_PATH<-'../data/find_map.csv'
OLD_FIND_MAP_PATH<-url("https://raw.githubusercontent.com/PandemicPreventionInstitute/NGS-Capacity-map/main/data/LMIC%20centered%20map/NGS_flourish_file_11.9.2021_TEST3.csv")
LMIC_LIST_PATH<-'../data/list_of_LMICS.csv'


```
Read in data
```{r}
find_df<-read.csv(FIND_MAP_PATH) 
old_find_df<-read.csv(OLD_FIND_MAP_PATH)
LMICs_df<-read.csv(LMIC_LIST_PATH)
LMICs_df<-LMICs_df%>%mutate(
  code = countrycode(LMICs, origin = 'country.name', destination = 'iso3c')
)%>%select(code)

# order the archetypes
find_df$archetype_clean<-factor(find_df$archetype_clean, ordered = TRUE, stringr::str_wrap(c("Test", "Connect", "Leverage", "Strengthen")))

max_test_cap_all_countries<-max(find_df$max_new_tests_cap_avg, na.rm = TRUE)
old_find_df<-old_find_df%>% select(code, archetype_full, max_new_tests_cap_avg, dx_testing_capacity)%>%
  rename(old_max_new_tests_cap_avg = max_new_tests_cap_avg,
         old_dx_testing_capacity = dx_testing_capacity,
         old_archetype = archetype_full)
# Make a data frame with country and new and old metrics for diagnostic capacity 
test_df<-left_join(find_df, old_find_df, by = "code")
# Subset to only LMICs!
test_df<-left_join(LMICs_df, test_df, by = "code")

countries_w_missing_data<-test_df%>%filter(max_new_tests_cap_avg==0 | is.na(max_new_tests_cap_avg) | 
                                  cases_in_last_90_days==0 | is.na(cases_in_last_90_days) |
                                  max_new_seq_cap_avg==0 | is.na(max_new_seq_cap_avg))
write.csv(countries_w_missing_data, '../data/countries_w_missing_data.csv')


                                       
# test_df<-test_df%>%
#   select(country, code, ngs_capacity, who_testing_capacity, dx_testing_capacity, max_new_tests_cap_avg,
#          tpr_90_days, cases_in_last_90_days, tests_in_last_90_days, old_max_new_tests_cap_avg, old_dx_testing_capacity, old_archetype, population_size)
# replace NAs with 0s
test_df$max_new_tests_cap_avg[is.na(test_df$max_new_tests_cap_avg)]<-0
#test_df$tpr_90_days[is.na(test_df$tpr_90_days)]<-1
test_df<-distinct(test_df)

countries_w_no_testing<-test_df%>%filter(max_new_tests_cap_avg==0 | is.na(max_new_tests_cap_avg))
countries_w_no_seq<-test_df%>%filter(max_new_seq_cap_avg==0 | is.na(max_new_seq_cap_avg))
countries_w_no_cases<-test_df%>%filter(cases_in_last_90_days==0 | is.na(cases_in_last_90_days))

countries_w_no_cases_tests<-test_df%>%filter(max_new_tests_cap_avg==0 | is.na(max_new_tests_cap_avg) |
                                                 cases_in_last_90_days==0 | is.na(cases_in_last_90_days))
# list of country codes with no cases or tests reported
countries_w_minimal_data<-countries_w_no_cases_tests$code

# Filter out these 7 countries and analyze countries with sufficient data 
test_df<-test_df%>%filter(!code %in% countries_w_minimal_data)
                                     
```

Bar charts of highest and lowest sequencing capacity countries
```{r}
test_df<-test_df[order(-test_df$sequences_in_last_90_days),]
test_df$country<-factor(test_df$country, ordered = TRUE)
test_df_upper<-test_df[1:25,]
test_df_lower<-test_df[(nrow(test_df)-25):nrow(test_df),]
test_df_upper$country <- factor(test_df_upper$country, levels =
                                    test_df_upper$country[order(test_df_upper$sequences_in_last_90_days)])
test_df_lower$country <- factor(test_df_lower$country, levels =
                                    test_df_lower$country[order(test_df_lower$sequences_in_last_90_days)])

bar_seq<-ggplot(test_df_upper) + geom_bar(aes(x =country, y = sequences_in_last_90_days, fill = sequencing_capacity), stat = "identity", position = "dodge") + 
  ylab('Cases sequenced in the past 90 days')+xlab('Country')+
  theme(axis.text.x = element_text(angle = 90)) + coord_flip() + 
    #ggtitle('Best 25 LMICs Sequences in past 90 days') + 
    labs(fill = "facilities")
bar_seq

bar_seq_lower<-ggplot(test_df_lower) + geom_bar(aes(x =country, y = sequences_in_last_90_days, fill = sequencing_capacity), stat = "identity", position = "dodge") + 
  ylab('Cases sequenced in past 90 days')+xlab('Country')+
  theme(axis.text.x = element_text(angle = 90)) + coord_flip() + 
    #ggtitle('Worst 25 LMICs sequences in past 90 days') + 
    labs(fill = "NGS facilities")
bar_seq_lower

test_df<-test_df[order(-test_df$max_new_seq_cap_avg),]
test_df$country<-factor(test_df$country, ordered = TRUE)
test_df_upper<-test_df[1:25,]
test_df_lower<-test_df[(nrow(test_df)-25):nrow(test_df),]
test_df_upper$country <- factor(test_df_upper$country, levels =
                                    test_df_upper$country[order(test_df_upper$max_new_seq_cap_avg)])
test_df_lower$country <- factor(test_df_lower$country, levels =
                                    test_df_lower$country[order(test_df_lower$max_new_seq_cap_avg)])

bar_seq<-ggplot(test_df_upper) + geom_bar(aes(x =country, y = max_new_seq_cap_avg, fill = sequencing_capacity), stat = "identity", position = "dodge") + 
  ylab('Max sequencing capacity per 100k')+xlab('Country')+
  theme(axis.text.x = element_text(angle = 90)) + coord_flip() + 
    #ggtitle('Best 25 LMICs Sequencing capacity') + 
    labs(fill = "NGS facilities")
bar_seq

bar_seq<-ggplot(test_df_lower) + geom_bar(aes(x =country, y = max_new_seq_cap_avg, fill = sequencing_capacity), stat = "identity", position = "dodge") + 
  ylab('Max sequencing capacity per 100k')+xlab('Country')+
  theme(axis.text.x = element_text(angle = 90)) + coord_flip() + 
    #ggtitle('Worst 25 LMICs Sequencing capacity') + 
    labs(fill = "NGS facilities")
bar_seq

test_df<-test_df[order(-test_df$percent_of_recent_cases_sequenced),]
test_df$country<-factor(test_df$country, ordered = TRUE)
test_df_upper<-test_df[1:25,]
test_df_lower<-test_df[(nrow(test_df)-25):nrow(test_df),]
test_df_upper$country <- factor(test_df_upper$country, levels =
                                    test_df_upper$country[order(test_df_upper$percent_of_recent_cases_sequenced)])
test_df_lower$country <- factor(test_df_lower$country, levels =
                                    test_df_lower$country[order(test_df_lower$percent_of_recent_cases_sequenced)])

bar_seq<-ggplot(test_df_upper) + geom_bar(aes(x =country, y = percent_of_recent_cases_sequenced, fill = sequencing_capacity), stat = "identity", position = "dodge") + 
  ylab('% cases sequenced')+xlab('Country')+
  theme(axis.text.x = element_text(angle = 90)) + coord_flip() + 
    #ggtitle('Best 25 LMICs Sequencing capacity') + 
    labs(fill = "NGS facilities")
bar_seq

bar_seq<-ggplot(test_df_lower) + geom_bar(aes(x =country, y = percent_of_recent_cases_sequenced, fill = sequencing_capacity), stat = "identity", position = "dodge") + 
  ylab('% cases sequenced')+xlab('Country')+
  theme(axis.text.x = element_text(angle = 90)) + coord_flip() + 
    #ggtitle('Worst 25 LMICs Sequencing capacity') + 
    labs(fill = "NGS facilities")
bar_seq
```

Scatterplot comparing the 3 metrics
```{r}
pct_seq_v_seq_cap<-ggplot(test_df) + geom_point(aes(y = percent_of_recent_cases_sequenced, x = max_new_seq_cap_avg, color = factor(sequencing_capacity),shape = old_archetype))+
    scale_x_log10()+
    coord_cartesian(ylim = c(0, 1))+
    xlab('Maximum of 90-day average of sequencing per 100k') + 
  ylab('% of recent cases sequenced')+ labs(shape = "Original archetype", color = "NGS facilities capacity")+
    scale_color_brewer(palette = "Set2")
pct_seq_v_seq_cap

pct_seq_v_seq<-ggplot(test_df) + geom_point(aes(y = percent_of_recent_cases_sequenced, x = sequences_in_last_90_days, color = factor(sequencing_capacity),shape = old_archetype))+
    scale_x_log10()+
    coord_cartesian(ylim = c(0, 1))+
    xlab('Cases sequenced in last 90 days') + 
  ylab('% of recent cases sequenced')+ labs(shape = "Original archetype", color = "NGS facilities capacity")+
    scale_color_brewer(palette = "Set2")
pct_seq_v_seq
```