---
title: "case_and_test_exploration"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
find_testing_US_t<-find_testing_t%>%filter(country== "Brazil")%>%
  filter(date>=(LAST_DATA_PULL_DATE-364) & 
           date<= LAST_DATA_PULL_DATE)
tpr<-sum(find_testing_US_t$new_cases_orig, na.rm = TRUE)/sum(find_testing_US_t$new_tests_orig, na.rm = TRUE)
tpr_smoothed<-sum(find_testing_US_t$new_cases_smoothed, na.rm = TRUE)/sum(find_testing_US_t$new_tests_smoothed, na.rm = TRUE)
med_tpr<-median(find_testing_US_t$pos, na.rm = TRUE)

plot_tests<-ggplot(find_testing_US_t) + geom_line(aes(x = date, y = tests_7d_avg), color = "blue") +
    geom_line(aes(x = date, y = new_tests_smoothed), color = "red") + geom_bar(aes(x = date, y = new_tests_orig), 
                                                                               fill = "blue", alpha = 0.1, stat = "identity")+
    xlab("Date") + ylab(" Reported Tests") + scale_y_log10()+
    ggtitle('USA tests last 90 days')
plot_tests

plot_cases<-ggplot(find_testing_US_t) + geom_line(aes(x = date, y = cases_7d_avg), color = "blue") +
    geom_line(aes(x = date, y = new_cases_smoothed), color = "red") + geom_bar(aes(x = date, y = new_cases_orig),
                                                                               fill = "blue", alpha = 0.1, stat = "identity")+
    xlab("Date") + ylab(" Reported Cases")+
    ggtitle('Brazil cases past year')
plot_cases

plot_tpr<-ggplot(find_testing_US_t) + geom_line(aes(x = date, y = pos), color = "black") +
    xlab("Date") + ylab("Daily TPR from 'all_new_tests'")+
    ggtitle('Brazil TPR')
plot_tpr
```